language: java

dist: xenial

sudo: false

jdk:
  - openjdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "nn4GGXnlQpRlt4IcgeEgmMKSA4byJu42P2Tf3h7fSnbX4LmacecAXn8Z3gvkSu1RWKbmMAKW3y7I2NASy8npyy4MM2/3a56Wm8TXCH44kndt24V5pXcgsogU/lDDz2wRuoIo371ZUylf6yezf4Dbc1cphxKRazDulxJH3Kp1wKI="

addons:
  coverity_scan:
    # https://docs.travis-ci.com/user/coverity-scan/
    project:
      name: "senbox-org/s2tbx"
      description: "Build submitted via Travis CI"
    notification_email: stb-coverity@thor.si.c-s.fr
    #build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true clean compile"
    branch_pattern: coverity_scan

install:
  - true

script:
  - mvn clean install -B -V

